Use standardized CI config. Support bookworm and bullseye CI jobs and requirements files.
Compile build requirements with Python 3.9.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,81 +1,168 @@
 ---
 common-steps:
-  - &removevirtualenv
+  - &install_testing_dependencies
     run:
-      name: Removes the upstream virtualenv from the original container image
-      command: sudo pip uninstall virtualenv -y
-
-  - &run_tests
-    run:
-      name: Install requirements and run tests
+      name: Install testing dependencies
       command: |
+        set -e
+        apt update && apt install -y git gnupg make python3-dev gnupg python3-venv libnotify-bin
+  - &install_build_dependencies
+    run:
+      name: Install build dependencies
+      command: |
+        set -e
+        apt update && apt install -y git make sudo
+  - &run_unit_tests
+    run:
+      name: Install requirements and run unit tests
+      command: |
+        set -e
+        export VERSION_CODENAME=$(~/project/scripts/codename)
         make venv
         source .venv/bin/activate
-        make check
-
+        make test
+  - &run_lint
+    run:
+      name: Run lint, type checking, code formatting
+      command: |
+        set -e
+        export VERSION_CODENAME=$(~/project/scripts/codename)
+        make venv
+        source .venv/bin/activate
+        make lint mypy
+  - &check_security
+    run:
+      name: Run static analysis on source code to find security issues
+      command: |
+        set -e
+        export VERSION_CODENAME=$(~/project/scripts/codename)
+        make venv
+        source .venv/bin/activate
+        make bandit
+  - &check_python_dependencies_for_vulnerabilities
+    run:
+      name: Check Python dependencies for known vulnerabilities
+      command: |
+        set -e
+        export VERSION_CODENAME=$(~/project/scripts/codename)
+        make venv
+        source .venv/bin/activate
+        make safety
   - &install_packaging_dependencies
     run:
-      name: Install Debian packaging dependencies and download wheels
+      name: Install Debian packaging dependencies and download Python wheels
       command: |
+        set -x
         mkdir ~/packaging && cd ~/packaging
-        git config --global --unset url.ssh://git@github.com.insteadof
+        # local builds may not have an ssh url, so || true
+        git config --global --unset url.ssh://git@github.com.insteadof || true
         git clone https://github.com/freedomofpress/securedrop-debian-packaging.git
         cd securedrop-debian-packaging
+        apt-get update && apt-get install -y sudo make
         make install-deps
         PKG_DIR=~/project make requirements
-
-  - &verify_requirements
+  - &check_packaging_requirements
     run:
-      name: Ensure that build-requirements.txt and requirements.txt are in sync.
+      name: Ensure that the same Python requirements are used for packaging and production.
       command: |
         cd ~/project
-        # Return 1 if unstaged changes exist (after `make requirements` in the
-        # previous run step), else return 0.
-        git diff --quiet
-
-  - &make_source_tarball
+        # Fail if unstaged changes exist (after `make requirements` in the previous run step).
+        git diff --ignore-matching-lines=# --exit-code
+  - &check_testing_requirements
     run:
-      name: Tag and make source tarball
+      name: Ensure that the same Python requirements are used for development/testing and production.
       command: |
-        cd ~/project
-        ./update_version.sh 1000.0  # Dummy version number, doesn't matter what we put here
-        python3 setup.py sdist
-
+        set -e
+        export VERSION_CODENAME=$(~/project/scripts/codename)
+        make venv
+        source .venv/bin/activate
+        make requirements
+        git diff --ignore-matching-lines=# --exit-code
   - &build_debian_package
     run:
       name: Build debian package
       command: |
         cd ~/packaging/securedrop-debian-packaging
         export PKG_VERSION=1000.0
-        export PKG_PATH=/home/circleci/project/dist/securedrop-proxy-$PKG_VERSION.tar.gz
+        export PKG_PATH=~/project/
         make securedrop-proxy
+version: 2.1
 
-version: 2
 jobs:
-  build-buster:
-    docker:
-      - image: circleci/python:3.7-buster
+  build:
+    parameters: &parameters
+      image:
+        type: string
+    docker: &docker
+      - image: debian:<< parameters.image >>
     steps:
+      - *install_build_dependencies
       - checkout
-      - *removevirtualenv
       - *install_packaging_dependencies
-      - *verify_requirements
-      - *make_source_tarball
+      - *check_packaging_requirements
       - *build_debian_package
 
-  test-buster:
-    docker:
-      - image: circleci/python:3.7-buster
+  unit-test:
+    parameters: *parameters
+    docker: *docker
     steps:
+      - *install_testing_dependencies
       - checkout
-      - *run_tests
+      - *run_unit_tests
+      - store_test_results:
+          path: test-results
+
+  lint:
+    parameters: *parameters
+    docker: *docker
+    steps:
+      - *install_testing_dependencies
+      - checkout
+      - *run_lint
+
+  check-security:
+    parameters: *parameters
+    docker: *docker
+    steps:
+      - *install_testing_dependencies
+      - checkout
+      - *check_security
+
+  check-python-security:
+    parameters: *parameters
+    docker: *docker
+    steps:
+      - *install_testing_dependencies
+      - checkout
+      - *check_python_dependencies_for_vulnerabilities
+
+  check-testing-requirements:
+    parameters: *parameters
+    docker: *docker
+    steps:
+      - *install_testing_dependencies
+      - checkout
+      - *check_testing_requirements
 
 workflows:
-  version: 2
-  securedrop_proxy_ci:
-    jobs:
-      - test-buster
-      - build-buster
+  securedrop_export_ci:
+    jobs: &jobs
+      - unit-test:
+          matrix: &matrix
+            parameters:
+              image:
+                - bullseye
+                - bookworm
+      - lint:
+          matrix: *matrix
+      - check-testing-requirements:
+          matrix: *matrix
+      - check-security:
+          matrix: *matrix
+      - check-python-security:
+          matrix: *matrix
+      - build:
+          matrix: *matrix
 
   nightly:
     triggers:
@@ -85,6 +172,4 @@ workflows:
             branches:
               only:
                 - main
-    jobs:
-      - test-buster
-      - build-buster
+    jobs: *jobs
